# version: "3"
# services:

#   client:
#     build: 
#       context: ./client
#       dockerfile: Dockerfile
#     ports:
#       - 3000:3000
#     networks:
#       - mern-network
#     volumes:
#       - ./client/src:/usr/app/src
#       - ./client/public:/usr/app/public
#     # depends_on:
#     #   - server
#     environment:
#       - REACT_APP_SERVER=http://localhost:3000
#       - CHOKIDAR_USEPOLLING=true
#     command: npm start
#     stdin_open: true
#     tty: true

version: '3.7'

services:

  sample:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/src:/usr/app/src
      - ./client/public:/usr/app/public
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - mern-network
    depends_on:
      - server


  
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - mern-network
    volumes:
      - ./server:/usr/app
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017
      - CLIENT=http://localhost:3000
    
# original DB which worked
  # db:
  #   container_name: mongo_db
  #   image: mongo:3.6.19-xenial
  #   ports:
  #     - 27017:27017
  #   networks:
  #     - mern-network
  #   volumes:
  #     - mongo-data:/data/db
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=root
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
  db:
    image: mongo
    container_name: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - mern-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      # MONGO_INITDB_DATABASE: golfStats

networks:
  mern-network:
    driver: bridge

volumes:
  mongodata:
    driver: local


